/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentation;

import Main.Main;
import business.user_business;

/**
 *
 * @author TIN
 */
public class pro_presentation extends javax.swing.JFrame {

    /**
     * Creates new form pro_presentation
     */
    public pro_presentation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        name = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        name_tf = new javax.swing.JTextField();
        usname_tf = new javax.swing.JTextField();
        pass_tf = new javax.swing.JPasswordField();
        dob_lb = new javax.swing.JLabel();
        year = new javax.swing.JTextField();
        edit_name = new javax.swing.JButton();
        edit_pass = new javax.swing.JButton();
        edit_dob = new javax.swing.JButton();
        day = new javax.swing.JTextField();
        month = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setText("Name");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 43, -1, -1));

        email.setText("Username");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 78, -1, -1));

        pass.setText("Password");
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 112, -1, -1));

        name_tf.setText(Main.us.getFullname());
        getContentPane().add(name_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 40, 197, -1));

        usname_tf.setText(Main.us.getUsername());
        getContentPane().add(usname_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 75, 197, -1));

        pass_tf.setText(Main.us.getPassword());
        getContentPane().add(pass_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 109, 197, -1));

        dob_lb.setText("Date of birth");
        getContentPane().add(dob_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 153, -1, -1));

        year.setText(Integer.toString(Main.us.getDob().getYear()));
        getContentPane().add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 150, 77, -1));

        edit_name.setText("Edit");
        edit_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_nameActionPerformed(evt);
            }
        });
        getContentPane().add(edit_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 40, -1, -1));

        edit_pass.setText("Edit");
        edit_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_passActionPerformed(evt);
            }
        });
        getContentPane().add(edit_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 109, -1, -1));

        edit_dob.setText("Edit");
        edit_dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_dobActionPerformed(evt);
            }
        });
        getContentPane().add(edit_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 150, -1, -1));

        day.setText(Integer.toString(Main.us.getDob().getDayOfMonth()));
        getContentPane().add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 150, 28, -1));

        month.setText(Integer.toString(Main.us.getDob().getMonthValue()));
        getContentPane().add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 28, -1));

        jLabel1.setText("Level: " + Main.us.getRole());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 191, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Profile");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(title)
                .addContainerGap(206, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(title)
                .addContainerGap())
        );

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(33, 33, 33))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 450, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edit_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_passActionPerformed
        // TODO add your handling code here:
        user_business us_bus = new user_business();
        us_bus.change_pass(new String(pass_tf.getPassword()), Main.us.getId());
    }//GEN-LAST:event_edit_passActionPerformed

    private void edit_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_nameActionPerformed
        // TODO add your handling code here:
        user_business us_bus = new user_business();
        us_bus.update_name(name_tf.getText(), Main.us.getId());
    }//GEN-LAST:event_edit_nameActionPerformed

    private void edit_dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_dobActionPerformed
        // TODO add your handling code here:
        user_business us_bus = new user_business();
        String d = day.getText();
        String m = month.getText();
        String y = year.getText();
        d = d.replaceAll("\\s", "");
        m = m.replaceAll("\\s", "");
        y = y.replaceAll("\\s", "");
        if (!d.equals("") && !m.equals("") && !y.equals("")) {
            if (d.length() < 2) {
                d = "0" + d;
            }
            if (m.length() < 2) {
                m = "0" + m;
            }
            if (y.length() == 3) {
                y = "0" + y;
            }
            if (y.length() == 2) {
                y = "00" + y;
            }
            if (y.length() == 1) {
                y = "000" + y;
            }
            String dob = y+"-"+m+"-"+d;
            us_bus.update_dob(dob, Main.us.getId());
        }
    }//GEN-LAST:event_edit_dobActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pro_presentation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pro_presentation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pro_presentation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pro_presentation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                login_presentation login = new login_presentation();
                //new pro_presentation().setVisible(true);
                login.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField day;
    private javax.swing.JLabel dob_lb;
    private javax.swing.JButton edit_dob;
    private javax.swing.JButton edit_name;
    private javax.swing.JButton edit_pass;
    private javax.swing.JLabel email;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField month;
    private javax.swing.JLabel name;
    private javax.swing.JTextField name_tf;
    private javax.swing.JLabel pass;
    private javax.swing.JPasswordField pass_tf;
    private javax.swing.JLabel title;
    private javax.swing.JTextField usname_tf;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
